spring.application.name=baozi-store

# Banco de Dados H2 em Memória
spring.datasource.url=jdbc:h2:mem:baozidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate/JPA - Cria as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console Web do H2 (Acessível via http://localhost:8080/h2-console)
spring.h2.console.enabled=true